# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/PortlandState/ECE_544/Labs/544_Final_Project/Vivado_FinalProject/Vivado_FinalProject.srcs/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
# IP: The module: 'embsys_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PortlandState/ECE_544/Labs/544_Final_Project/Vivado_FinalProject/Vivado_FinalProject.gen/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/PortlandState/ECE_544/Labs/544_Final_Project/Vivado_FinalProject/Vivado_FinalProject.srcs/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
# IP: The module: 'embsys_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PortlandState/ECE_544/Labs/544_Final_Project/Vivado_FinalProject/Vivado_FinalProject.gen/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
