
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_BTN_SW_DEVICE_ID,
		XPAR_AXI_GPIO_BTN_SW_BASEADDR,
		XPAR_AXI_GPIO_BTN_SW_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_BTN_SW_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_LED_DEVICE_ID,
		XPAR_AXI_GPIO_LED_BASEADDR,
		XPAR_AXI_GPIO_LED_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_LED_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_RLY_DEVICE_ID,
		XPAR_AXI_GPIO_RLY_BASEADDR,
		XPAR_AXI_GPIO_RLY_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_RLY_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_X_CNT_DEVICE_ID,
		XPAR_AXI_GPIO_X_CNT_BASEADDR,
		XPAR_AXI_GPIO_X_CNT_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_X_CNT_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_Y_CNT_DEVICE_ID,
		XPAR_AXI_GPIO_Y_CNT_BASEADDR,
		XPAR_AXI_GPIO_Y_CNT_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_Y_CNT_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_Z_CNT_DEVICE_ID,
		XPAR_AXI_GPIO_Z_CNT_BASEADDR,
		XPAR_AXI_GPIO_Z_CNT_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_Z_CNT_IS_DUAL
	}
};


