# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/PortlandState/ECE_544/Labs/project_1/Project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_green_low_0/embsys_axi_gpio_green_low_0.xci
# IP: The module: 'embsys_axi_gpio_green_low_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PortlandState/ECE_544/Labs/project_1/Project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_green_low_0/embsys_axi_gpio_green_low_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_green_low_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/PortlandState/ECE_544/Labs/project_1/Project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_green_low_0/embsys_axi_gpio_green_low_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_green_low_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/PortlandState/ECE_544/Labs/project_1/Project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_green_low_0/embsys_axi_gpio_green_low_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_green_low_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/PortlandState/ECE_544/Labs/project_1/Project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_green_low_0/embsys_axi_gpio_green_low_0.xci
# IP: The module: 'embsys_axi_gpio_green_low_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PortlandState/ECE_544/Labs/project_1/Project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_green_low_0/embsys_axi_gpio_green_low_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_green_low_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/PortlandState/ECE_544/Labs/project_1/Project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_green_low_0/embsys_axi_gpio_green_low_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_green_low_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/PortlandState/ECE_544/Labs/project_1/Project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_green_low_0/embsys_axi_gpio_green_low_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_green_low_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
